document.addEventListener("DOMContentLoaded", function () {
  let cart = JSON.parse(localStorage.getItem("krunchiezCart") || "[]");
  const cartPanel=document.getElementById("cartPanel"), overlay=document.getElementById("overlay"), cartItems=document.getElementById("cartItems"), cartTotal=document.getElementById("cartTotal"), toast=document.getElementById("toast");
  function saveCart(){localStorage.setItem("krunchiezCart",JSON.stringify(cart));}
  function total(){return cart.reduce((s,i)=>s+i.price*i.quantity,0);}
  function count(){return cart.reduce((s,i)=>s+i.quantity,0);}
  function updateCount(){document.querySelectorAll("#cartCount").forEach(x=>x.textContent=count());}
  function toastMsg(m){if(!toast)return;toast.textContent=m;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1800);}
  function renderDrawer(){if(!cartItems)return;cartItems.innerHTML=cart.length?cart.map((i,n)=>`<div class="cart-item"><div class="cart-item-info"><strong>${i.name}</strong><span>₹${i.price} × ${i.quantity}</span></div><div class="cart-item-actions"><button data-action="decrease" data-index="${n}">−</button><span>${i.quantity}</span><button data-action="increase" data-index="${n}">+</button><button data-action="remove" data-index="${n}">Remove</button></div></div>`).join(""):'<p class="empty">Your cart is waiting for a crunch.</p>';if(cartTotal)cartTotal.textContent="₹"+total();updateCount();}
  function open(){cartPanel?.classList.add("open");overlay?.classList.add("show");renderDrawer();}
  function close(){cartPanel?.classList.remove("open");overlay?.classList.remove("show");}
  document.addEventListener("click",e=>{const b=e.target.closest(".add-btn");if(b){const name=b.dataset.name,price=Number(b.dataset.price),weight=b.dataset.weight||"52 g";let item=cart.find(x=>x.name===name);if(item)item.quantity++;else cart.push({name,price,weight,quantity:1});saveCart();renderDrawer();toastMsg(name+" added to cart ✓");} if(e.target.closest("#openCart")){e.preventDefault();open();} if(e.target.closest("#closeCart")){e.preventDefault();close();} const a=e.target.closest("#cartItems [data-action]");if(a){const i=Number(a.dataset.index);if(a.dataset.action==='increase')cart[i].quantity++;if(a.dataset.action==='decrease'){cart[i].quantity--;if(cart[i].quantity<=0)cart.splice(i,1)}if(a.dataset.action==='remove')cart.splice(i,1);saveCart();renderDrawer();}});
  overlay?.addEventListener("click",close);document.addEventListener("keydown",e=>{if(e.key==='Escape')close();});
  function goCheckout(){if(!cart.length){toastMsg("Your cart is empty!");return;}location.href="checkout.html";}
  document.addEventListener("click",e=>{if(e.target.closest("#checkoutBtn"))goCheckout();if(e.target.closest("#fullCheckoutBtn"))goCheckout();});
  function renderFullCart(){const box=document.getElementById("fullCartItems");if(!box)return;const empty=document.getElementById("fullCartEmpty"),sum=document.getElementById("fullCartSummary");if(!cart.length){box.innerHTML="";empty.style.display="block";sum.style.display="none";return;}empty.style.display="none";sum.style.display="block";box.innerHTML=cart.map((i,n)=>`<div class="cart-page-row"><strong>${i.name}<br><small>${i.weight}</small></strong><span>₹${i.price}</span><span class="qty-controls"><button data-full-action="dec" data-index="${n}">−</button>${i.quantity}<button data-full-action="inc" data-index="${n}">+</button></span><span>₹${i.price*i.quantity} <button class="remove-col" data-full-action="remove" data-index="${n}">Remove</button></span></div>`).join("");document.getElementById("fullCartTotal").textContent="₹"+total();document.getElementById("fullCartTotal2").textContent="₹"+total();}
  document.addEventListener("click",e=>{const b=e.target.closest("[data-full-action]");if(!b)return;const i=Number(b.dataset.index);if(b.dataset.fullAction==='inc')cart[i].quantity++;if(b.dataset.fullAction==='dec'){cart[i].quantity--;if(cart[i].quantity<=0)cart.splice(i,1)}if(b.dataset.fullAction==='remove')cart.splice(i,1);saveCart();renderFullCart();renderDrawer();});
  function renderCheckout(){const box=document.getElementById("checkoutItems");if(!box)return;if(!cart.length){location.href='shop.html';return;}box.innerHTML=cart.map(i=>`<div class="order-summary-row"><span>${i.name} × ${i.quantity}</span><strong>₹${i.price*i.quantity}</strong></div>`).join("");document.getElementById("checkoutTotal").textContent="₹"+total();}
  const form=document.getElementById("checkoutPageForm");if(form)form.addEventListener("submit",e=>{e.preventDefault();const name=document.getElementById("customerName").value.trim(),phone=document.getElementById("customerPhone").value.trim(),address=document.getElementById("customerAddress").value.trim();if(!/^\d{10}$/.test(phone)){alert("Please enter a valid 10-digit phone number.");return;}fetch("https://krunchiez-backend.krunchiezfoodspvt-ltd.workers.dev/create-order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer:{name,phone,address},items:cart,total:total()})}).then(r=>r.json()).then(d=>{if(d.success){localStorage.setItem("krunchiezLastOrder",JSON.stringify({name,total:total()}));cart=[];saveCart();location.href="order-success.html";}else alert("Something went wrong. Please try again.");}).catch(err=>{console.error(err);alert("Could not connect to Krunchiez server.");});});
  function renderProduct(){const data={"peri-peri":{name:"PERI PERI",tag:"SPICY & ZESTY",price:32,image:"./assets/peri-peri.jpg",desc:"Spicy, zesty and made for snack attacks."},"madness-masala":{name:"MADNESS MASALA",tag:"DESI BOLD FLAVOUR",price:32,image:"./assets/madness-masala.jpg",desc:"Desi masala energy with a seriously bold crunch."},caramel:{name:"CARAMEL",tag:"SWEET & CRUNCHY",price:42,image:"./assets/caramel.jpg",desc:"Sweet, crunchy and irresistibly snackable."}};const key=new URLSearchParams(location.search).get("product")||"peri-peri",p=data[key]||data["peri-peri"];const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v};set("productName",p.name);set("productTag",p.tag);set("productPrice","₹"+p.price+" · 52 g");set("productDescription",p.desc);set("productLong",p.desc);const img=document.getElementById("productImage");if(img){img.src=p.image;img.alt="Krunchiez "+p.name+" popcorn";}const add=document.getElementById("productAdd");if(add){add.dataset.name=p.name.split(' ').map(x=>x[0]+x.slice(1).toLowerCase()).join(' ');if(key==='peri-peri')add.dataset.name='Peri Peri';if(key==='madness-masala')add.dataset.name='Madness Masala';if(key==='caramel')add.dataset.name='Caramel';add.dataset.price=p.price;add.dataset.weight='52 g';}}
  renderDrawer();renderFullCart();renderCheckout();renderProduct();
});